import numpy as np
import pandas as pd
import os
import re

data_loc = "data/length-of-stay/"
train_folder = os.path.join(data_loc, "train")
test_folder = os.path.join(data_loc, "test")
new_train_folder = os.path.join(data_loc, "train_upd")
new_test_folder = os.path.join(data_loc, "test_upd")

# create new data folders
if not os.path.exists(new_train_folder):
    os.makedirs(new_train_folder)

if not os.path.exists(new_test_folder):
    os.makedirs(new_test_folder)

# move listfile from original to newly udated folders
os.rename(os.path.join(train_folder, "listfile.csv"),
        os.path.join(new_train_folder, "listfile.csv"))
os.rename(os.path.join(test_folder, "listfile.csv"),
        os.path.join(new_test_folder, "listfile.csv"))

# read in new data generated by group
demo_data = pd.read_csv("./demographic_data.csv",
        usecols = ["filename", "insurance", "ethnicity_group", "marital_status_group", "gender"])

sent_data = pd.read_csv("./notes_sentiment_data.csv",
        usecols = ["filename", "notes_sentiment"])

all_data = demo_data.merge(sent_data, how="left")

# run through train data
train_files = os.listdir(train_folder)
# train_files = [f for f in train_files if re.search("episode", f)]
# x = list(set(train_files) - set(all_data["filename"]))

for i in train_files:
    episode_data = pd.read_csv(os.path.join(train_folder, i), dtype=str)
    match = all_data[all_data["filename"].values == i]

    # episode_data["insurance"] = ""
    # episode_data.at[0, "insurance"] = match.iloc[0]["insurance"]
    episode_data["insurance"] = match.iloc[0]["insurance"]
    episode_data["ethnicity_group"] = match.iloc[0]["ethnicity_group"]
    episode_data["marital_status_group"] = match.iloc[0]["marital_status_group"]
    episode_data["gender"] = match.iloc[0]["gender"]
    episode_data["notes_sentiment"] = match.iloc[0]["notes_sentiment"]

    episode_data.to_csv(os.path.join(new_train_folder, i), index=False)

test_files = os.listdir(test_folder)
# train_files = [f for f in train_files if re.search("episode", f)]

for i in test_files:
    episode_data = pd.read_csv(os.path.join(test_folder, i), dtype=str)
    match = all_data[all_data["filename"].values == i]

    # episode_data["insurance"] = ""
    # episode_data.at[0, "insurance"] = match.iloc[0]["insurance"]
    episode_data["insurance"] = match.iloc[0]["insurance"]
    episode_data["ethnicity_group"] = match.iloc[0]["ethnicity_group"]
    episode_data["marital_status_group"] = match.iloc[0]["marital_status_group"]
    episode_data["gender"] = match.iloc[0]["gender"]
    episode_data["notes_sentiment"] = match.iloc[0]["notes_sentiment"]

    episode_data.to_csv(os.path.join(new_test_folder, i), index=False)

